<a href="https://colab.research.google.com/github/Meiyi-Wu/blooket-hack/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
np_city = np.array(["NYC","LA","Miami","Houston"])
np_city_state = np.array([[["NYC","LA","Miami","Houston"],["NY","CA","FL","TX"],[100,200,50,5]]])

print(np_city_state)
np_city_state.ndim


[[['NYC' 'LA' 'Miami' 'Houston']
  ['NY' 'CA' 'FL' 'TX']
  ['100' '200' '50' '5']]]


3

In [ ]:
trial_1=[10,15,17,26]
trial_2=[2]
np_trial_1=np.array(trial_1)
np_trial_2=np.array(trial_2)
np_total =np_trial_1/np_trial_2
np_total

all = np.array([[10,15,17,26],[12,11,21,24]])
all

#first_trial = all[0]
#second_trial = all[1]
#first_element = all[0,1]
#first_element



array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [ ]:
trial_1=[10,15,17,26]
trial_2=[2]
np_trial_1=np.array(trial_1)
np_trial_2=np.array(trial_2)
np_total =np_trial_1/np_trial_2
np_total

all = np.array([[10,15,17,26],[12,11,21,24]])
all[1,0]
all[1,3]
first_trial = all[0]
second_trial = all[1]

print(second_trial[1])


all[1,1]

11


11

In [ ]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
pass_scores = test_scores >60
print(pass_score)

[[ True  True False  True]
 [False  True  True False]]


In [ ]:
test_scores= np.array([[83,71,57,63], [54,68,81,45]])

pass_score = test_scores > 60

array_pass = test_scores[pass_score]

print(sorted(array_pass))

[63, 68, 71, 81, 83]


In [ ]:
NYC_Borough = np.array(["manhattan", "Bronx", "Brooklyn", "Queens", "Staten Island"])
NYC_Borough

Boroughs_In_NYC = NYC_Borough
Boroughs_In_NYC in NYC_Borough

True

In [ ]:
Boroughs_In_NYC
view_Boroughs_In_NYC = Boroughs_In_NYC.view()

view_Boroughs_In_NYC[4] = 'Central Park'
print(view_Boroughs_In_NYC)
print(Boroughs_In_NYC)

['manhattan' 'Bronx' 'Brooklyn' 'Queens' 'Central Park']
['manhattan' 'Bronx' 'Brooklyn' 'Queens' 'Central Park']


In [ ]:
copy_of_Boroughs_In_NYC = NYC_Borough.copy()
copy_of_Boroughs_In_NYC
NYC_Borough

copy_of_Boroughs_In_NYC[4] = 'Staten Island'
copy_of_Boroughs_In_NYC
NYC_Borough

array(['manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Central Park'],
      dtype='<U13')

In [ ]:
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt
from numpy import pi
np.sin(pi/2)
np.cos(pi)
np.floor([1.5,2.3,6.7])

np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [ ]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
print(test_scores)
print(test_scores.transpose())

[[83 71 57 63]
 [54 68 81 45]]
[[83 54]
 [71 68]
 [57 81]
 [63 45]]


In [ ]:
10^-1

-11